name: Ubuntu 20.04 & GCC 10 & Qt 6

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Install tools
      run: |
        sudo apt update
        sudo apt --yes install g++-10 cmake qtbase6-dev

    - name: Build
      run: |
        mkdir out
        cd out
        export CC=/usr/bin/gcc-10
        export CXX=/usr/bin/g++-10
        cmake ..
        make